labe-food/src/components/Filter/Filter.js, labe-food/src/components/Filter/Styled.js, labe-food/src/components/RestaurantCard/RestaurantCard.js, labe-food/src/pages/FeedPage/FeedPage.js
=> Cards já redirecionam para a página do restaurante específico!

labe-food/src/components/Filter/Filter.js, labe-food/src/components/Filter/Styled.js, labe-food/src/pages/FeedPage/FeedPage.js
Falta linkar com os "botões" das categorias do Filter
=> Filtro por categoria está funcionando alterando o estado manualmente!

labe-food/src/App.js, labe-food/src/Hooks/useRequestData.js, labe-food/src/global/GlobalState.js, labe-food/src/global/GlobalStateContext.js, labe-food/src/pages/RestaurantPage/RestaurantPage.js, labe-food/src/pages/RestaurantPage/Styled.js
=> Criação do GlobalState e renderizacao dos produtos

labe-food/src/constants/BASE_URL.js, labe-food/src/pages/FeedPage/FeedPage.js, labe-food/src/pages/ProfilePage/ProfilePage.js
Falta só termos pedidos através do GET Order History para finalizar os cards
=> Lógica de histórico de pedidos feita!

labe-food/src/components/RestaurantProductCard/RestaurantProductCard.js, labe-food/src/global/GlobalState.js, labe-food/src/pages/CartPage/CartPage.jsx, labe-food/src/pages/RestaurantPage/RestaurantPage.js
=> add e remover produtos

labe-food/src/components/RestaurantProductCard/RestaurantProductCard.js, labe-food/src/global/GlobalState.js, labe-food/src/pages/CartPage/CartPage.jsx, labe-food/src/pages/FeedPage/FeedPage.js, labe-food/src/pages/RestaurantPage/RestaurantPage.js
=> cart funcionando

labe-food/src/components/Modal/Modal.js, labe-food/src/components/RestaurantProductCard/RestaurantProductCard.js, labe-food/src/components/RestaurantProductCard/Styled.js, labe-food/src/pages/RestaurantPage/RestaurantPage.js, labe-food/src/pages/RestaurantPage/Styled.js
=> finalizando estilização restaurantPage

labe-food/package-lock.json, labe-food/package.json, labe-food/src/components/Filter/Filter.js, labe-food/src/components/Footer/Styled.jsx, labe-food/src/components/RestaurantCard/RestaurantCard.js, labe-food/src/components/RestaurantCard/Styled.js, labe-food/src/pages/FeedPage/FeedPage.js, labe-food/src/pages/FeedPage/Styled.js
=> ultima pr fechada corrigida

labe-food/src/pages/SplashPage/SplashPage.js, labe-food/src/pages/SplashPage/SplashPage.jsx, labe-food/src/routes/Coordinator.js, labe-food/src/routes/Router.js
=> splash adicionada e transformada na home

labe-food/src/components/Header/Header.js, labe-food/src/components/Header/Styled.js, labe-food/src/components/Modal/Modal.js, labe-food/src/pages/AdressFormPage/AdressFormPage.js, labe-food/src/pages/CartPage/CartPage.jsx, labe-food/src/pages/CartPage/Styled.js, labe-food/src/pages/EditAdressPage/EditAdressPage.js, labe-food/src/pages/EditProfilePage/EditProfilePage.js, labe-food/src/pages/FeedPage/FeedPage.js, labe-food/src/pages/ProfilePage/ProfilePage.js, labe-food/src/pages/RestaurantPage/RestaurantPage.js, labe-food/src/pages/SignUpPage/SignUpPage.js
=> Finalizando estilização carrinho

labe-food/src/components/RestaurantProductCard/RestaurantProductCard.js, labe-food/src/pages/FeedPage/FeedPage.js
=> Resolvendo conflitos

labe-food/src/components/Cart/Cart.jsx, labe-food/src/components/Modal/Modal.js, labe-food/src/components/RestaurantProductCard/RestaurantProductCard.js, labe-food/src/global/GlobalState.js, labe-food/src/pages/CartPage/CartPage.jsx
=> carrinho funcionando

labe-food/src/Hooks/useRequestData.js, labe-food/src/components/Address/NewAddressForm.js, labe-food/src/components/Address/UpdateAdressForm.js, labe-food/src/components/Cart/Cart.jsx, labe-food/src/components/Cart/Styled.js, labe-food/src/components/Modal/Modal.js, labe-food/src/components/OrderInProgress/Styled.jsx, labe-food/src/components/RestaurantCard/RestaurantCard.js, labe-food/src/components/RestaurantProductCard/RestaurantProductCard.js, labe-food/src/components/UpdateProfile/UpdateProfile.js, labe-food/src/global/GlobalState.js, labe-food/src/pages/CartPage/CartPage.jsx, labe-food/src/pages/ProfilePage/ProfilePage.js, labe-food/src/services/GetUserInfo.js
=> retirada dos console.log e acertos na estilização do carrinho

labe-food/src/components/Cart/Cart.jsx, labe-food/src/components/RestaurantCard/Styled.js, labe-food/src/components/UpdateProfile/UpdateProfile.js, labe-food/src/global/GlobalState.js, labe-food/src/pages/CartPage/CartPage.jsx
=> Bug Formulario

labe-food/src/components/Address/NewAddressForm.js, labe-food/src/components/Address/UpdateAdressForm.js, labe-food/src/components/UpdateProfile/UpdateProfile.js, labe-food/src/global/GlobalState.js
=> aplicando a logica de permanencia de dados para o editAddress

labe-food/src/components/Address/UpdateAdressForm.js, labe-food/src/components/Login/LoginForm.js, labe-food/src/components/UpdateProfile/UpdateProfile.js, labe-food/src/global/GlobalState.js, labe-food/src/pages/LoginPage/LoginPage.js, labe-food/src/pages/ProfilePage/ProfilePage.js
=> permanencia de dados funcionando - aleluia!

labe-food/src/components/SignUp/SignUpForm.js, labe-food/src/pages/LoginPage/LoginPage.js, labe-food/src/pages/ProfilePage/ProfilePage.js, labe-food/src/pages/SignUpPage/SignUpPage.js
=> deletando console.logs, modificando alerts e protegendo paginas

labe-food/src/components/Address/NewAddressForm.js, labe-food/src/components/Address/UpdateAdressForm.js, labe-food/src/components/Modal/Modal.js, labe-food/src/components/UpdateProfile/UpdateProfile.js, labe-food/src/global/GlobalState.js, labe-food/src/pages/CartPage/CartPage.jsx, labe-food/src/pages/FeedPage/FeedPage.js, labe-food/src/pages/ProfilePage/ProfilePage.js, labe-food/src/pages/RestaurantPage/RestaurantPage.js
=> Headers will

labe-food/src/global/GlobalState.js, labe-food/src/pages/FeedPage/FeedPage.js, labe-food/src/pages/ProfilePage/ProfilePage.js
=> Alterando headers de algumas requisições

labe-food/src/pages/FeedPage/FeedPage.js, labe-food/src/pages/ProfilePage/ProfilePage.js
=> resolvendo alerts de nao autorizado no feed e profile

labe-food/src/components/Address/NewAddressForm.js, labe-food/src/components/Address/UpdateAdressForm.js, labe-food/src/components/Address/style.jsx, labe-food/src/components/Login/LoginForm.js, labe-food/src/components/Login/styled.jsx, labe-food/src/components/SignUp/SignUpForm.js, labe-food/src/components/SignUp/styled.jsx, labe-food/src/components/UpdateProfile/UpdateProfile.js, labe-food/src/components/UpdateProfile/style.jsx, labe-food/src/pages/LoginPage/LoginPage.js, labe-food/src/pages/LoginPage/styled.jsx, labe-food/src/pages/SignUpPage/SignUpPage.js
=> todos os forms finalizados

labe-food/src/components/Modal/Modal.js, labe-food/src/components/RestaurantProductCard/RestaurantProductCard.js
=> Debug cart will
